<?php

 // Auto generated by wpfluent Installer.

 return array (
  'name' => 'FluentForm',
  'slug' => 'fluentform',
  'domain_path' => 'resources/language',
  'text_domain' => 'fluentform',
  'hook_prefix' => 'fluentform',
  'rest_namespace' => 'fluentform',
  'rest_version' => 'v2',
  'env'            => 'dev',
);
