<?php

/**
 * Builds dev/COVERAGE-STATUS.md from the Clover coverage report produced by
 * `./wpf coverage`. Buckets every covered file into a module and writes a
 * per-module table plus the least-covered files — the board contributors watch
 * as Waves 2A–2E fill coverage in. Invoked via ./wpf coverage:status.
 */
return function ($cwd) {
    $clover = $cwd . '/dev/wp-browser/tests/_output/coverage.xml';

    if (!is_file($clover)) {
        die("No coverage report found at dev/wp-browser/tests/_output/coverage.xml\nRun: ./wpf coverage\n");
    }

    $xml = @simplexml_load_file($clover);
    if (!$xml) {
        die("Could not parse {$clover}\n");
    }

    $bucketOf = function ($path) {
        $path = str_replace('\\', '/', $path);
        if (preg_match('#/app/Modules/([^/]+)#', $path, $m)) {
            return 'Modules/' . $m[1];
        }
        if (preg_match('#/app/Http/Controllers#', $path)) {
            return 'Http/Controllers';
        }
        if (preg_match('#/app/Http/Policies#', $path)) {
            return 'Http/Policies';
        }
        if (preg_match('#/app/Services/([^/]+)#', $path, $m)) {
            return 'Services/' . $m[1];
        }
        if (preg_match('#/app/Models#', $path)) {
            return 'Models';
        }
        if (preg_match('#/app/([^/]+)#', $path, $m)) {
            return $m[1];
        }
        return 'other';
    };

    $modules = [];
    $files = [];

    foreach ($xml->xpath('//file') as $file) {
        $name = (string) $file['name'];
        $metrics = $file->metrics;
        if (!$metrics) {
            continue;
        }
        $statements = (int) $metrics['statements'];
        $covered = (int) $metrics['coveredstatements'];
        if ($statements === 0) {
            continue;
        }

        $bucket = $bucketOf($name);
        if (!isset($modules[$bucket])) {
            $modules[$bucket] = ['covered' => 0, 'total' => 0];
        }
        $modules[$bucket]['covered'] += $covered;
        $modules[$bucket]['total'] += $statements;

        $files[] = [
            'file'    => preg_replace('#^.*/app/#', 'app/', str_replace('\\', '/', $name)),
            'percent' => $statements ? ($covered / $statements * 100) : 0,
            'total'   => $statements,
        ];
    }

    ksort($modules);

    $grandCovered = array_sum(array_column($modules, 'covered'));
    $grandTotal = array_sum(array_column($modules, 'total'));
    $grandPct = $grandTotal ? round($grandCovered / $grandTotal * 100, 1) : 0;

    $pct = function ($c, $t) {
        return $t ? round($c / $t * 100, 1) : 0;
    };

    $lines = [];
    $lines[] = '# Coverage Status';
    $lines[] = '';
    $lines[] = 'Generated by `./wpf coverage:status` from the latest `./wpf coverage` run.';
    $lines[] = '';
    $lines[] = "**Overall: {$grandPct}%** ({$grandCovered}/{$grandTotal} statements)";
    $lines[] = '';
    $lines[] = '## Per-module';
    $lines[] = '';
    $lines[] = '| Module | Coverage | Covered / Total |';
    $lines[] = '|--------|---------:|----------------:|';
    foreach ($modules as $name => $m) {
        $p = $pct($m['covered'], $m['total']);
        $lines[] = "| {$name} | {$p}% | {$m['covered']} / {$m['total']} |";
    }

    usort($files, function ($a, $b) {
        return $a['percent'] <=> $b['percent'];
    });
    $lowest = array_slice($files, 0, 10);

    $lines[] = '';
    $lines[] = '## Least-covered files (top 10)';
    $lines[] = '';
    $lines[] = '| File | Coverage | Statements |';
    $lines[] = '|------|---------:|-----------:|';
    foreach ($lowest as $f) {
        $lines[] = '| ' . $f['file'] . ' | ' . round($f['percent'], 1) . '% | ' . $f['total'] . ' |';
    }
    $lines[] = '';

    $target = $cwd . '/dev/COVERAGE-STATUS.md';
    file_put_contents($target, implode("\n", $lines));
    echo "Wrote {$target} — overall {$grandPct}%\n";
};
